### ISSUE TITLE
SIGABRT (0.72.1)

### ISSUE THREAD

**Issue by dt-atkinson** [medooze/media-server-node#111]
This is on an old medooze version (0.72.1, production isn't upgraded to latest yet) so possibly closable if this code has changed - however I got a SIGABRT on my production stack:

```
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f8e037fe700 (LWP 3998))]
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f8e1c60f801 in __GI_abort () at abort.c:79
#2  0x00007f8e1c5ff39a in __assert_fail_base (fmt=0x7f8e1c7867d8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x7f8e1c9d4692 "mutex->__data.__owner == 0", 
    file=file@entry=0x7f8e1c9d4675 "../nptl/pthread_mutex_lock.c", line=line@entry=79, 
    function=function@entry=0x7f8e1c9d4800 <__PRETTY_FUNCTION__.8734> "__pthread_mutex_lock") at assert.c:92
#3  0x00007f8e1c5ff412 in __GI___assert_fail (assertion=assertion@entry=0x7f8e1c9d4692 "mutex->__data.__owner == 0", 
    file=file@entry=0x7f8e1c9d4675 "../nptl/pthread_mutex_lock.c", line=line@entry=79, 
    function=function@entry=0x7f8e1c9d4800 <__PRETTY_FUNCTION__.8734> "__pthread_mutex_lock") at assert.c:101
#4  0x00007f8e1c9ca1c8 in __GI___pthread_mutex_lock (mutex=mutex@entry=0xa52a140) at ../nptl/pthread_mutex_lock.c:79
#5  0x00007f8e19a8abd9 in Mutex::Lock (this=0xa52a140) at ../media-server/include/use.h:105
#6  ScopedLock::ScopedLock (m=..., this=<synthetic pointer>) at ../media-server/include/use.h:218
#7  RTPIncomingMediaStreamMultiplexer::<lambda(...)>::operator() (__closure=0x7f8e037fd138)
    at ../media-server/src/rtp/RTPIncomingMediaStreamMultiplexer.cpp:76
#8  std::_Function_handler<void(std::chrono::duration<long int, std::ratio<1, 1000> >), RTPIncomingMediaStreamMultiplexer::onEnded(RTPIncomingMediaStream*)::<lambda(...)> >::_M_invoke(const std::_Any_data &, std::chrono::duration<long, std::ratio<1, 1000> > &&) (__functor=..., __args#0=...) at /usr/include/c++/7/bits/std_function.h:316
#9  0x00007f8e19a35cb9 in std::function<void (std::chrono::duration<long, std::ratio<1l, 1000l> >)>::operator()(std::chrono::duration<long, std::ratio<1l, 1000l> >) const (__args#0=..., this=0x7f8e037fd138) at /usr/include/c++/7/bits/std_function.h:706
#10 EventLoop::Run (this=<optimized out>, duration=...) at ../media-server/src/EventLoop.cpp:535
#11 0x00007f8e19a37802 in EventLoop::<lambda(...)>::operator() (__closure=<optimized out>)
    at ../media-server/src/EventLoop.cpp:155
#12 std::__invoke_impl<void, EventLoop::Start(int)::<lambda(...)> > (__f=...) at /usr/include/c++/7/bits/invoke.h:60
#13 std::__invoke<EventLoop::Start(int)::<lambda(...)> > (__fn=...) at /usr/include/c++/7/bits/invoke.h:95
#14 std::thread::_Invoker<std::tuple<EventLoop::Start(int)::<lambda(...)> > >::_M_invoke<0> (this=<optimized out>)
    at /usr/include/c++/7/thread:234
#15 std::thread::_Invoker<std::tuple<EventLoop::Start(int)::<lambda(...)> > >::operator() (this=<optimized out>)
    at /usr/include/c++/7/thread:243
#16 std::thread::_State_impl<std::thread::_Invoker<std::tuple<EventLoop::Start(int)::<lambda(...)> > > >::_M_run(void) (
    this=<optimized out>) at /usr/include/c++/7/thread:186
#17 0x00007f8e1d25266f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#18 0x00007f8e1c9c76db in start_thread (arg=0x7f8e037fe700) at pthread_create.c:463
#19 0x00007f8e1c6f088f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) 

```

**Comment by murillo128** [comment]
I think that the issue is that the c++ object was called while there were async calls being executed referencing that object. I have added a destructor to wait for the async calls to be executed, should not happen again.
