### ISSUE TITLE
Segmentation fault on dtlsstatechange event after object ha been disposed (0.77.3)

### ISSUE THREAD

**Issue by dt-atkinson** [medooze/media-server-node#112]
New seg fault!
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000b2c636 in v8::Object::Get(v8::Local<v8::Value>) ()
[Current thread is 1 (Thread 0x7fb21744b740 (LWP 3262))]
(gdb) bt
#0  0x0000000000b2c636 in v8::Object::Get(v8::Local<v8::Value>) ()
#1  0x00007fb214322e07 in DTLSICETransportListener::onDTLSStateChanged(DTLSICETransport::DTLSState)::{lambda()#1}::operator()() const (__closure=<optimized out>) at ../src/media-server_wrap.cxx:2243
#2  std::_Function_handler<void (), DTLSICETransportListener::onDTLSStateChanged(DTLSICETransport::DTLSState)::{lambda()#1}>::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/include/c++/7/bits/std_function.h:316
#3  0x00007fb214320bd3 in std::function<void ()>::operator()() const (this=0x7ffc4500e270)
    at /usr/include/c++/7/bits/std_function.h:706
#4  MediaServer::async_cb_handler (handle=<optimized out>) at ../src/media-server_wrap.cxx:1772
#5  0x0000000000a6f52f in uv__async_io (loop=0x2655860 <default_loop_struct>, w=<optimized out>, events=<optimized out>)
    at ../deps/uv/src/unix/async.c:118
#6  0x0000000000a80dd8 in uv__io_poll (loop=loop@entry=0x2655860 <default_loop_struct>, timeout=0)
    at ../deps/uv/src/unix/linux-core.c:379
#7  0x0000000000a6fe6b in uv_run (loop=0x2655860 <default_loop_struct>, mode=UV_RUN_DEFAULT) at ../deps/uv/src/unix/core.c:364
#8  0x0000000000904725 in node::Start(v8::Isolate*, node::IsolateData*, std::vector<std::string, std::allocator<std::string> > const&, std::vector<std::string, std::allocator<std::string> > const&) ()
#9  0x000000000090297f in node::Start(int, char**) ()
#10 0x00007fb215ef8b97 in __libc_start_main (main=0x8bbd50 <main>, argc=2, argv=0x7ffc450125c8, init=<optimized out>, 
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffc450125b8) at ../csu/libc-start.c:310
#11 0x00000000008bbe85 in _start ()
(gdb) 
```

**Comment by murillo128** [comment]
I have refactored the event callbacks from c++ to node and added extra checks, should not seg fault now. Reopen if it keeps failing.

**Comment by dt-atkinson** [comment]
Awesome, will test is out soon!
