### ISSUE TITLE
Deadlock (0.77.4)

### ISSUE THREAD

**Issue by dt-atkinson** [medooze/media-server-node#113]
```
(gdb) thread apply all bt

Thread 13 (Thread 0x7fa35f7fe700 (LWP 3868)):
#0  0x00007fa375878bf9 in __GI___poll (fds=fds@entry=0x38e3734, nfds=nfds@entry=2, timeout=-1)
    at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007fa3743ca124 in poll (__timeout=<optimized out>, __nfds=2, __fds=0x38e3734)
    at /usr/include/x86_64-linux-gnu/bits/poll2.h:46
#2  EventLoop::Run (this=<optimized out>, duration=...) at ../media-server/src/EventLoop.cpp:461
#3  0x00007fa3743ccac2 in EventLoop::<lambda(...)>::operator() (__closure=<optimized out>)
    at ../media-server/src/EventLoop.cpp:155
#4  std::__invoke_impl<void, EventLoop::Start(int)::<lambda(...)> > (__f=...) at /usr/include/c++/7/bits/invoke.h:60
#5  std::__invoke<EventLoop::Start(int)::<lambda(...)> > (__fn=...) at /usr/include/c++/7/bits/invoke.h:95
#6  std::thread::_Invoker<std::tuple<EventLoop::Start(int)::<lambda(...)> > >::_M_invoke<0> (this=<optimized out>)
    at /usr/include/c++/7/thread:234
#7  std::thread::_Invoker<std::tuple<EventLoop::Start(int)::<lambda(...)> > >::operator() (this=<optimized out>)
    at /usr/include/c++/7/thread:243
#8  std::thread::_State_impl<std::thread::_Invoker<std::tuple<EventLoop::Start(int)::<lambda(...)> > > >::_M_run(void) (
    this=<optimized out>) at /usr/include/c++/7/thread:186
#9  0x00007fa3763e766f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#10 0x00007fa375b5c6db in start_thread (arg=0x7fa35f7fe700) at pthread_create.c:463
#11 0x00007fa37588588f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 12 (Thread 0x7fa35ffff700 (LWP 3867)):
#0  0x00007fa375878bf9 in __GI___poll (fds=fds@entry=0x37aafa4, nfds=nfds@entry=2, timeout=-1)
    at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007fa3743ca124 in poll (__timeout=<optimized out>, __nfds=2, __fds=0x37aafa4)
    at /usr/include/x86_64-linux-gnu/bits/poll2.h:46
#2  EventLoop::Run (this=<optimized out>, duration=...) at ../media-server/src/EventLoop.cpp:461
#3  0x00007fa3743ccac2 in EventLoop::<lambda(...)>::operator() (__closure=<optimized out>)
    at ../media-server/src/EventLoop.cpp:155
#4  std::__invoke_impl<void, EventLoop::Start(int)::<lambda(...)> > (__f=...) at /usr/include/c++/7/bits/invoke.h:60
#5  std::__invoke<EventLoop::Start(int)::<lambda(...)> > (__fn=...) at /usr/include/c++/7/bits/invoke.h:95
#6  std::thread::_Invoker<std::tuple<EventLoop::Start(int)::<lambda(...)> > >::_M_invoke<0> (this=<optimized out>)
    at /usr/include/c++/7/thread:234
#7  std::thread::_Invoker<std::tuple<EventLoop::Start(int)::<lambda(...)> > >::operator() (this=<optimized out>)
    at /usr/include/c++/7/thread:243
#8  std::thread::_State_impl<std::thread::_Invoker<std::tuple<EventLoop::Start(int)::<lambda(...)> > > >::_M_run(void) (
    this=<optimized out>) at /usr/include/c++/7/thread:186
#9  0x00007fa3763e766f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#10 0x00007fa375b5c6db in start_thread (arg=0x7fa35ffff700) at pthread_create.c:463
#11 0x00007fa37588588f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 11 (Thread 0x7fa36cff9700 (LWP 3865)):
#0  0x00007fa375b629f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x265582c <cond+44>)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x26557c0 <mutex>, cond=0x2655800 <cond>) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=cond@entry=0x2655800 <cond>, mutex=mutex@entry=0x26557c0 <mutex>)
    at pthread_cond_wait.c:655
#3  0x0000000000a7de09 in uv_cond_wait (cond=cond@entry=0x2655800 <cond>, mutex=mutex@entry=0x26557c0 <mutex>)
    at ../deps/uv/src/unix/thread.c:760
#4  0x0000000000a6ac3e in worker (arg=0x0) at ../deps/uv/src/threadpool.c:76
#5  0x00007fa375b5c6db in start_thread (arg=0x7fa36cff9700) at pthread_create.c:463
#6  0x00007fa37588588f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

---Type <return> to continue, or q <return> to quit---
Thread 10 (Thread 0x7fa36d7fa700 (LWP 3864)):
#0  0x00007fa375b629f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x265582c <cond+44>)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x26557c0 <mutex>, cond=0x2655800 <cond>) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=cond@entry=0x2655800 <cond>, mutex=mutex@entry=0x26557c0 <mutex>)
    at pthread_cond_wait.c:655
#3  0x0000000000a7de09 in uv_cond_wait (cond=cond@entry=0x2655800 <cond>, mutex=mutex@entry=0x26557c0 <mutex>)
    at ../deps/uv/src/unix/thread.c:760
#4  0x0000000000a6ac3e in worker (arg=0x0) at ../deps/uv/src/threadpool.c:76
#5  0x00007fa375b5c6db in start_thread (arg=0x7fa36d7fa700) at pthread_create.c:463
#6  0x00007fa37588588f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 9 (Thread 0x7fa36dffb700 (LWP 3863)):
#0  0x00007fa375b629f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x265582c <cond+44>)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x26557c0 <mutex>, cond=0x2655800 <cond>) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=cond@entry=0x2655800 <cond>, mutex=mutex@entry=0x26557c0 <mutex>)
    at pthread_cond_wait.c:655
#3  0x0000000000a7de09 in uv_cond_wait (cond=cond@entry=0x2655800 <cond>, mutex=mutex@entry=0x26557c0 <mutex>)
    at ../deps/uv/src/unix/thread.c:760
#4  0x0000000000a6ac3e in worker (arg=0x0) at ../deps/uv/src/threadpool.c:76
#5  0x00007fa375b5c6db in start_thread (arg=0x7fa36dffb700) at pthread_create.c:463
#6  0x00007fa37588588f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 8 (Thread 0x7fa36e7fc700 (LWP 3862)):
#0  0x00007fa375b629f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x265582c <cond+44>)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x26557c0 <mutex>, cond=0x2655800 <cond>) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=cond@entry=0x2655800 <cond>, mutex=mutex@entry=0x26557c0 <mutex>)
    at pthread_cond_wait.c:655
#3  0x0000000000a7de09 in uv_cond_wait (cond=cond@entry=0x2655800 <cond>, mutex=mutex@entry=0x26557c0 <mutex>)
    at ../deps/uv/src/unix/thread.c:760
#4  0x0000000000a6ac3e in worker (arg=0x0) at ../deps/uv/src/threadpool.c:76
#5  0x00007fa375b5c6db in start_thread (arg=0x7fa36e7fc700) at pthread_create.c:463
#6  0x00007fa37588588f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 7 (Thread 0x7fa376ce5700 (LWP 3849)):
#0  0x00007fa375b656d6 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, 
    futex_word=0x2654a20 <node::inspector::(anonymous namespace)::start_io_thread_semaphore>)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x2654a20 <node::inspector::(anonymous namespace)::start_io_thread_semaphore>, 
    abstime=0x0) at sem_waitcommon.c:111
#2  0x00007fa375b657c8 in __new_sem_wait_slow (
    sem=sem@entry=0x2654a20 <node::inspector::(anonymous namespace)::start_io_thread_semaphore>, abstime=0x0)
    at sem_waitcommon.c:181
#3  0x00007fa375b65839 in __new_sem_wait (
    sem=sem@entry=0x2654a20 <node::inspector::(anonymous namespace)::start_io_thread_semaphore>) at sem_wait.c:42
#4  0x0000000000a7dbe2 in uv__sem_wait (sem=<optimized out>) at ../deps/uv/src/unix/thread.c:604
#5  uv_sem_wait (sem=0x2654a20 <node::inspector::(anonymous namespace)::start_io_thread_semaphore>)
    at ../deps/uv/src/unix/thread.c:660
#6  0x00000000009ec482 in node::inspector::(anonymous namespace)::StartIoThreadMain(void*) ()
#7  0x00007fa375b5c6db in start_thread (arg=0x7fa376ce5700) at pthread_create.c:463
#8  0x00007fa37588588f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
---Type <return> to continue, or q <return> to quit---

Thread 6 (Thread 0x7fa36effd700 (LWP 3848)):
#0  0x00007fa375b629f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x36a8abc)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x36a8a68, cond=0x36a8a90) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x36a8a90, mutex=0x36a8a68) at pthread_cond_wait.c:655
#3  0x0000000000a7de09 in uv_cond_wait (cond=<optimized out>, mutex=<optimized out>) at ../deps/uv/src/unix/thread.c:760
#4  0x0000000000980a74 in node::BackgroundRunner(void*) ()
#5  0x00007fa375b5c6db in start_thread (arg=0x7fa36effd700) at pthread_create.c:463
#6  0x00007fa37588588f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 5 (Thread 0x7fa36f7fe700 (LWP 3847)):
#0  0x00007fa375b629f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x36a8abc)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x36a8a68, cond=0x36a8a90) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x36a8a90, mutex=0x36a8a68) at pthread_cond_wait.c:655
#3  0x0000000000a7de09 in uv_cond_wait (cond=<optimized out>, mutex=<optimized out>) at ../deps/uv/src/unix/thread.c:760
#4  0x0000000000980a74 in node::BackgroundRunner(void*) ()
#5  0x00007fa375b5c6db in start_thread (arg=0x7fa36f7fe700) at pthread_create.c:463
#6  0x00007fa37588588f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 4 (Thread 0x7fa36ffff700 (LWP 3846)):
#0  0x00007fa375b629f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x36a8abc)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x36a8a68, cond=0x36a8a90) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x36a8a90, mutex=0x36a8a68) at pthread_cond_wait.c:655
#3  0x0000000000a7de09 in uv_cond_wait (cond=<optimized out>, mutex=<optimized out>) at ../deps/uv/src/unix/thread.c:760
#4  0x0000000000980a74 in node::BackgroundRunner(void*) ()
#5  0x00007fa375b5c6db in start_thread (arg=0x7fa36ffff700) at pthread_create.c:463
#6  0x00007fa37588588f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7fa374f62700 (LWP 3845)):
#0  0x00007fa375b629f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x36a8abc)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x36a8a68, cond=0x36a8a90) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x36a8a90, mutex=0x36a8a68) at pthread_cond_wait.c:655
#3  0x0000000000a7de09 in uv_cond_wait (cond=<optimized out>, mutex=<optimized out>) at ../deps/uv/src/unix/thread.c:760
#4  0x0000000000980a74 in node::BackgroundRunner(void*) ()
#5  0x00007fa375b5c6db in start_thread (arg=0x7fa374f62700) at pthread_create.c:463
#6  0x00007fa37588588f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7fa375763700 (LWP 3844)):
#0  0x00007fa3758859ee in __GI_epoll_pwait (epfd=13, events=events@entry=0x7fa37575fe00, 
    maxevents=maxevents@entry=1024, timeout=timeout@entry=-1, set=set@entry=0x0)
    at ../sysdeps/unix/sysv/linux/epoll_pwait.c:42
#1  0x0000000000a80c5f in uv__io_poll (loop=loop@entry=0x36a9198, timeout=-1) at ../deps/uv/src/unix/linux-core.c:279
#2  0x0000000000a6fe6b in uv_run (loop=0x36a9198, mode=UV_RUN_DEFAULT) at ../deps/uv/src/unix/core.c:364
#3  0x00000000009843d8 in node::BackgroundTaskRunner::DelayedTaskScheduler::Start()::{lambda(void*)#1}::_FUN(void*) ()
#4  0x00007fa375b5c6db in start_thread (arg=0x7fa375763700) at pthread_create.c:463
#5  0x00007fa37588588f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7fa376cd8740 (LWP 3837)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
---Type <return> to continue, or q <return> to quit---
#1  0x00007fa3763e54d1 in std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration<long, std::ratio<1l, 1l> >, std::chrono::duration<long, std::ratio<1l, 1000000000l> >) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00007fa374425632 in std::__atomic_futex_unsigned<2147483648u>::_M_load_and_test_until (__ns=..., __s=..., 
    __has_timeout=<optimized out>, __mo=<optimized out>, __equal=<optimized out>, __operand=<optimized out>, 
    __assumed=<optimized out>, this=<optimized out>) at /usr/include/c++/7/bits/atomic_futex.h:102
#3  std::__atomic_futex_unsigned<2147483648u>::_M_load_and_test (__mo=<optimized out>, __equal=<optimized out>, 
    __operand=<optimized out>, __assumed=<optimized out>, this=<optimized out>)
    at /usr/include/c++/7/bits/atomic_futex.h:122
#4  std::__atomic_futex_unsigned<2147483648u>::_M_load_when_equal (__mo=std::memory_order_acquire, __val=1, 
    this=0x37abdf0) at /usr/include/c++/7/bits/atomic_futex.h:162
#5  std::__future_base::_State_baseV2::wait (this=0x37abde0) at /usr/include/c++/7/future:337
#6  std::__basic_future<void>::wait (this=0x7ffdab61ac30) at /usr/include/c++/7/future:692
#7  RTPIncomingMediaStreamMultiplexer::~RTPIncomingMediaStreamMultiplexer (this=0x39d0490, __in_chrg=<optimized out>)
    at ../media-server/src/rtp/RTPIncomingMediaStreamMultiplexer.cpp:14
#8  0x00007fa374425761 in RTPIncomingMediaStreamMultiplexer::~RTPIncomingMediaStreamMultiplexer (this=0x39d0490, 
    __in_chrg=<optimized out>) at ../media-server/src/rtp/RTPIncomingMediaStreamMultiplexer.cpp:15
#9  0x00007fa374386601 in _wrap_delete_RTPIncomingMediaStreamMultiplexer (data=...)
    at ../src/media-server_wrap.cxx:10572
#10 0x0000000000ec3873 in v8::internal::GlobalHandles::DispatchPendingPhantomCallbacks(bool) ()
#11 0x0000000000ec3a9a in v8::internal::GlobalHandles::PostGarbageCollectionProcessing(v8::internal::GarbageCollector, v8::GCCallbackFlags) ()
#12 0x0000000000f0069a in v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) ()
#13 0x0000000000f014c4 in v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) ()
#14 0x0000000000f01c9a in v8::internal::Heap::FinalizeIncrementalMarkingIfComplete(v8::internal::GarbageCollectionReason) ()
#15 0x0000000000f05377 in v8::internal::IncrementalMarkingJob::Task::RunInternal() ()
#16 0x0000000000bf63f6 in v8::internal::CancelableTask::Run() ()
#17 0x0000000000981a94 in node::PerIsolatePlatformData::RunForegroundTask(std::unique_ptr<v8::Task, std::default_delete<v8::Task> >) ()
#18 0x0000000000983172 in node::PerIsolatePlatformData::FlushForegroundTasksInternal() ()
#19 0x0000000000a6f52f in uv__async_io (loop=0x2655860 <default_loop_struct>, w=<optimized out>, events=<optimized out>)
    at ../deps/uv/src/unix/async.c:118
#20 0x0000000000a80dd8 in uv__io_poll (loop=loop@entry=0x2655860 <default_loop_struct>, timeout=200)
    at ../deps/uv/src/unix/linux-core.c:379
#21 0x0000000000a6fe6b in uv_run (loop=0x2655860 <default_loop_struct>, mode=UV_RUN_DEFAULT)
    at ../deps/uv/src/unix/core.c:364
#22 0x0000000000904725 in node::Start(v8::Isolate*, node::IsolateData*, std::vector<std::string, std::allocator<std::string> > const&, std::vector<std::string, std::allocator<std::string> > const&) ()
#23 0x000000000090297f in node::Start(int, char**) ()
#24 0x00007fa375785b97 in __libc_start_main (main=0x8bbd50 <main>, argc=2, argv=0x7ffdab61f4b8, init=<optimized out>, 
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffdab61f4a8) at ../csu/libc-start.c:310
#25 0x00000000008bbe85 in _start ()
(gdb) q

```

**Comment by murillo128** [comment]
is this the same as #98?

**Comment by murillo128** [comment]
This should not happen anymore with latest version as this code has been removed.

**Comment by dt-atkinson** [comment]
It is not the same deadlock - I haven't been using RTPSessions in this

**Comment by murillo128** [comment]
yes, I say it, it is the same cause than #114 the patch should solve both
