### ISSUE TITLE
Segfault (0.77.4)

### ISSUE THREAD

**Issue by dt-atkinson** [medooze/media-server-node#114]
Sorry, another segfault
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f054420d5db in RTPIncomingMediaStreamMultiplexer::~RTPIncomingMediaStreamMultiplexer (this=0x45bd7a0, __in_chrg=<optimized out>)
    at ../media-server/src/rtp/RTPIncomingMediaStreamMultiplexer.cpp:14
14		timeService.Async([=](...){}).wait();
[Current thread is 1 (Thread 0x7f0547ac2740 (LWP 4100))]
(gdb) bt
#0  0x00007f054420d5db in RTPIncomingMediaStreamMultiplexer::~RTPIncomingMediaStreamMultiplexer (this=0x45bd7a0, __in_chrg=<optimized out>)
    at ../media-server/src/rtp/RTPIncomingMediaStreamMultiplexer.cpp:14
#1  0x00007f054420d761 in RTPIncomingMediaStreamMultiplexer::~RTPIncomingMediaStreamMultiplexer (this=0x45bd7a0, __in_chrg=<optimized out>)
    at ../media-server/src/rtp/RTPIncomingMediaStreamMultiplexer.cpp:15
#2  0x00007f054416e601 in _wrap_delete_RTPIncomingMediaStreamMultiplexer (data=...) at ../src/media-server_wrap.cxx:10572
#3  0x0000000000ec3873 in v8::internal::GlobalHandles::DispatchPendingPhantomCallbacks(bool) ()
#4  0x0000000000ec3a9a in v8::internal::GlobalHandles::PostGarbageCollectionProcessing(v8::internal::GarbageCollector, v8::GCCallbackFlags)
    ()
#5  0x0000000000f0069a in v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) ()
#6  0x0000000000f014c4 in v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) ()
#7  0x0000000000f04131 in v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) ()
#8  0x0000000000ecd5b4 in v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) ()
#9  0x000000000116d73e in v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) ()
#10 0x000012032bd5be1d in ?? ()
#11 0x000012032bd5bd81 in ?? ()
#12 0x00007ffd1c1e93b0 in ?? ()
#13 0x0000000000000006 in ?? ()
#14 0x00007ffd1c1e9420 in ?? ()
#15 0x000012032bd9d8de in ?? ()
#16 0x0000002800000000 in ?? ()
#17 0x000012032bd118d5 in ?? ()
#18 0x00001ce19c17fbf1 in ?? ()
#19 0x00002bc58e802201 in ?? ()
#20 0x00001c33c2f829a1 in ?? ()
#21 0x000019b1a4603dc1 in ?? ()
#22 0x0000000000000000 in ?? ()
(gdb) 
```

**Comment by murillo128** [comment]
I have indeed overlooked at the problem  😓

**Comment by murillo128** [comment]
Refactored the mirroring disposal handling and added some tests to ensure it doesn't seg fault. Should not happen again (hopefully)

**Comment by dt-atkinson** [comment]
Not seen this since! Thanks
