### ISSUE TITLE
Can't install on linux subsystem for windows.

### ISSUE THREAD

**Issue by wyvasi** [medooze/media-server-node#127]
I have tried to Install Ubuntu 16.x, 18.x and Debian. 
Every time the build fails. 
Tried gcc-7, gcc-8 and gcc-9.

 npm install medooze-media-server 

  AR(target) Release/obj.target/external/mp4v2/libmp4v2.a
  AR(target) Release/obj.target/external/srtp/srtp.a
  COPY Release/srtp.a
cp: preserving times for 'Release/srtp.a': Operation not permitted
make: *** [external/srtp/libsrtp.target.mk:215: Release/srtp.a] Error 1
make: *** Waiting for unfinished jobs....
make: Leaving directory '/mnt/c/work/hh/node_modules/medooze-media-server/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.4.0-18362-Microsoft
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--jobs=max"
gyp ERR! cwd /mnt/c/work/hh/node_modules/medooze-media-server
gyp ERR! node -v v13.1.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok

**Comment by wyvasi** [comment]
works using node v.8.x
