### ISSUE TITLE
[Bug] TypeError: Cannot read property 'clone' of null in SDPManagerUnified

### ISSUE THREAD

**Issue by tiepviet** [medooze/media-server-node#154]
```sh
/app/node_modules/medooze-media-server/lib/SDPManagerUnified.js:166
					mediaInfo = this.localInfo.getMedia(transceiver.media).clone();
					                                                      ^

TypeError: Cannot read property 'clone' of null
    at SDPManagerUnified.createLocalDescription (/app/node_modules/medooze-media-server/lib/SDPManagerUnified.js:166:60)
    at EventEmitter.Participant.sdpManager.on (/app/dist/lib/participant.js:117:62)
    at EventEmitter.emit (events.js:198:13)
    at EventEmitter.emit (domain.js:448:20)
    at Timeout.setTimeout [as _onTimeout] (/app/node_modules/medooze-media-server/lib/SDPManagerUnified.js:240:18)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
error Command failed with exit code 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by murillo128** [comment]
could you paste a dump of the localInfo object and the capabilities info? also, could you explain how are you are doing the sdp O/A?

**Comment by tiepviet** [comment]
Sorry for my problem. I couldn't reproduce this bug. So, I will close it.

**Comment by murillo128** [comment]
If you happen to reproduce it, please feel free to re-open it.

**Comment by skmax** [comment]
@murillo128 Also experience the same error from time to time. Unfortunately, I could find out exact reproducing steps as well.

**Comment by tiepviet** [comment]
Recently this error appears frequently on our server. So, I will reopen this issue.
