### ISSUE TITLE
Compilation on Raspberry Pi fails

### ISSUE THREAD

**Issue by joshi11** [medooze/media-server-node#172]
The installation/compilation on RPI 3B fails:

[......]
CXX(target) Release/obj.target/medooze-media-server/src/media-server_wrap.o
  CXX(target) Release/obj.target/medooze-media-server/media-server/ext/crc32c/src/crc32c.o
  CXX(target) Release/obj.target/medooze-media-server/media-server/ext/crc32c/src/crc32c_portable.o
  CXX(target) Release/obj.target/medooze-media-server/media-server/ext/crc32c/src/crc32c_sse42.o
In file included from ../media-server/ext/crc32c/src/crc32c_portable.cc:10:
../media-server/ext/crc32c/src/./crc32c_prefetch.h:11:10: fatal error: crc32c/crc32c_config.h: No such file or directory
 #include "crc32c/crc32c_config.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from ../media-server/ext/crc32c/src/crc32c_sse42.cc:5:
../media-server/ext/crc32c/src/./crc32c_sse42.h:13:10: fatal error: crc32c/crc32c_config.h: No such file or directory
 #include "crc32c/crc32c_config.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [medooze-media-server.target.mk:255: Release/obj.target/medooze-media-server/media-server/ext/crc32c/src/crc32c_portable.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [medooze-media-server.target.mk:255: Release/obj.target/medooze-media-server/media-server/ext/crc32c/src/crc32c_sse42.o] Error 1
In file included from ../media-server/ext/crc32c/src/crc32c.cc:10:
../media-server/ext/crc32c/src/./crc32c_arm64.h:13:10: fatal error: crc32c/crc32c_config.h: No such file or directory
 #include "crc32c/crc32c_config.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [medooze-media-server.target.mk:255: Release/obj.target/medooze-media-server/media-server/ext/crc32c/src/crc32c.o] Error 1
[......]

System Information
------------------
Raspberry Pi 3 Model B Plus Rev 1.3
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
Linux rx1 5.4.79-v7+ #1373 SMP Mon Nov 23 13:22:33 GMT 2020 armv7l GNU/Linux

**Comment by joshi11** [comment]
The installation process goes on with plenty of errors and culminate in:

[...]
void SWIGV8_INIT (v8::Handle<v8::Object> exports, v8::Handle<v8::Object> /*module*/)
                                          ^~~~~~~
../src/media-server_wrap.cxx:15072:55: error: ‘Handle’ is not a member of ‘v8’
 void SWIGV8_INIT (v8::Handle<v8::Object> exports, v8::Handle<v8::Object> /*module*/)
                                                       ^~~~~~
../src/media-server_wrap.cxx:15072:55: note: suggested alternative: ‘JobHandle’
 void SWIGV8_INIT (v8::Handle<v8::Object> exports, v8::Handle<v8::Object> /*module*/)
                                                       ^~~~~~
                                                       JobHandle
../src/media-server_wrap.cxx:15072:72: error: expected primary-expression before ‘>’ token
 void SWIGV8_INIT (v8::Handle<v8::Object> exports, v8::Handle<v8::Object> /*module*/)
                                                                        ^
../src/media-server_wrap.cxx:15072:84: error: expected primary-expression before ‘)’ token
 void SWIGV8_INIT (v8::Handle<v8::Object> exports, v8::Handle<v8::Object> /*module*/)
                                                                                    ^
In file included from ../src/media-server_wrap.cxx:171:
../src/media-server_wrap.cxx:15932:22: error: ‘medooze_initialize’ was not declared in this scope
 NODE_MODULE(medooze, medooze_initialize)
                      ^~~~~~~~~~~~~~~~~~
/home/pi/.cache/node-gyp/14.16.0/include/node/node.h:758:36: note: in definition of macro ‘NODE_MODULE_X’
       (node::addon_register_func) (regfunc),                          \
                                    ^~~~~~~
../src/media-server_wrap.cxx:15932:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(medooze, medooze_initialize)
 ^~~~~~~~~~~
make: *** [medooze-media-server.target.mk:258: Release/obj.target/medooze-media-server/src/media-server_wrap.o] Error 1
make: Leaving directory '/home/pi/Web/medooze/media-server-demo-node/node_modules/medooze-media-server/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.4.79-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--jobs=max"
gyp ERR! cwd /home/pi/Web/medooze/media-server-demo-node/node_modules/medooze-media-server
gyp ERR! node -v v14.16.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! medooze-media-server@0.100.5 install: `test -f build/Release/medooze-media-server.node || (node-gyp configure && node-gyp rebuild --jobs=max)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the medooze-media-server@0.100.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by murillo128** [comment]
How are you compiling it?

Note that node v12 and v14 were not supported until today. see #80

**Comment by joshi11** [comment]
compiling: nothing fancy. just regular installation with npm as described  in Readme
I guess it will due to the node version... Didnt know that v12 and 14 wasnt supported. 
using v14.16.0 which is the current LTS version... 

So will try again with updates.
Thx

**Comment by joshi11** [comment]
tried to install using: npm i --save medooze-media-server

make: *** [medooze-media-server.target.mk:258: Release/obj.target/medooze-media-server/src/media-server_wrap.o] Error 1
make: Leaving directory '/home/pi/Web/medooze/media-server-demo-node/node_modules/medooze-media-server/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.4.79-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--jobs=max"
gyp ERR! cwd /home/pi/Web/medooze/media-server-demo-node/node_modules/medooze-media-server
gyp ERR! node -v v14.16.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! medooze-media-server@0.100.5 install: `test -f build/Release/medooze-media-server.node || (node-gyp configure && node-gyp rebuild --jobs=max)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the medooze-media-server@0.100.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by joshi11** [comment]
I cloned the project again since it git status said I am up to date but
log showed last commit from 3.3.2021
New to git (SVN user) - so just cloned again and got:

Versions: 
media-server-node:
commit 6a9b8f3c14f71dc1b52cea28b8dd3fb2bb34dd37 (HEAD -> master, origin/master, origin/HEAD)
Date:   Wed Mar 10 10:34:20 2021 +0100

npm: 6.14.11
nodejs: 14.16.0

Command: 
> git submodule update --init --recursive 
> npm i                

Error:
make: Leaving directory '/home/pi/Web/medooze/media-server-node/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.4.79-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--jobs=max"
gyp ERR! cwd /home/pi/Web/medooze/media-server-node
gyp ERR! node -v v14.16.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! medooze-media-server@0.100.5 install: `test -f build/Release/medooze-media-server.node || (node-gyp configure && node-gyp rebuild --jobs=max)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the medooze-media-server@0.100.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2021-03-10T18_22_30_183Z-debug.log

**Comment by murillo128** [comment]
could you send me the full debug log file?
