### ISSUE TITLE
Can not build on Arch Linux

### ISSUE THREAD

**Issue by kolserdav** [medooze/media-server-node#188]
While i run command `npm run dist` i get this error:

```bash
kol @ ~/Projects/media-server-node $ npm run dist

> medooze-media-server@0.118.0 dist /home/kol/Projects/media-server-node
> node-gyp configure && node-gyp build --jobs=max && mkdir -p dist && tar cvzf dist/medooze-media-server-`node -e 'console.log(require("./package.json").version)'`.tgz `([ "$(uname)" = 'Darwin' ] && echo "-s |^|medooze-media-server/|") || echo " --transform=flags=r;s|^|medooze-media-server/|"` package.json index.js medooze-media-server.d.ts README.md lib/* build/Release/medooze-media-server.node

make: Entering directory '/home/kol/Projects/media-server-node/build'
make: *** No rule to make target 'Release/obj.target/mp4v2/external/mp4v2/lib/libplatform/io/FileSystem_posix.o', needed by 'Release/obj.target/external/mp4v2/libmp4v2.a'.  Stop.
make: Leaving directory '/home/kol/Projects/media-server-node/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/kol/.nvm/versions/node/v10.24.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:191:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.16.4-arch1-1
gyp ERR! command "/home/kol/.nvm/versions/node/v10.24.1/bin/node" "/home/kol/.nvm/versions/node/v10.24.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--jobs=max"
gyp ERR! cwd /home/kol/Projects/media-server-node
gyp ERR! node -v v10.24.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! medooze-media-server@0.118.0 dist: `node-gyp configure && node-gyp build --jobs=max && mkdir -p dist && tar cvzf dist/medooze-media-server-`node -e 'console.log(require("./package.json").version)'`.tgz `([ "$(uname)" = 'Darwin' ] && echo "-s |^|medooze-media-server/|") || echo " --transform=flags=r;s|^|medooze-media-server/|"` package.json index.js medooze-media-server.d.ts README.md lib/* build/Release/medooze-media-server.node`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the medooze-media-server@0.118.0 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kol/.npm/_logs/2022-05-18T03_54_15_083Z-debug.log
```

**Comment by murillo128** [comment]
have you installled the submodules?

```
   git submodule update --init --recursive
```
