### ISSUE TITLE
Build failure with v0.46.0

### ISSUE THREAD

**Issue by Nicholi** [medooze/media-server-node#51]
Looks just like some things that got forgot in a commit. No problem building the previous tag (v0.45.0).

Reproduce with:
```
git clone https://github.com/medooze/media-server-node.git
cd media-server-node
git checkout tags/v0.46.0
git submodule init
git submodule update
npm i
npm run-script dist
```

```
../src/media-server_wrap.cxx: In function ‘SwigV8ReturnValue _wrap_DTLSICETransport_SetBandwidthProbing(const SwigV8Arguments&)’:
../src/media-server_wrap.cxx:11275:11: error: ‘class DTLSICETransport’ has no member named ‘SetBandwidthProbing’
   (arg1)->SetBandwidthProbing(arg2);
           ^~~~~~~~~~~~~~~~~~~
../src/media-server_wrap.cxx: In function ‘SwigV8ReturnValue _wrap_DTLSICETransport_SetMaxProbingBitrate(const SwigV8Arguments&)’:
../src/media-server_wrap.cxx:11311:11: error: ‘class DTLSICETransport’ has no member named ‘SetMaxProbingBitrate’
   (arg1)->SetMaxProbingBitrate(arg2);
           ^~~~~~~~~~~~~~~~~~~~
../src/media-server_wrap.cxx: In function ‘SwigV8ReturnValue _wrap_new_RTPSessionFacade(const SwigV8Arguments&)’:
../src/media-server_wrap.cxx:14377:57: warning: ‘new’ of type ‘RTPSessionFacade’ with extended alignment 32 [-Waligned-new=]
   result = (RTPSessionFacade *)new RTPSessionFacade(arg1);
                                                         ^
../src/media-server_wrap.cxx:14377:57: note: uses ‘void* operator new(std::size_t)’, which does not have an alignment parameter
../src/media-server_wrap.cxx:14377:57: note: use ‘-faligned-new’ to enable C++17 over-aligned new support
In file included from ../src/../media-server/include/rtp/RTPMap.h:18:0,
                 from ../src/../media-server/include/rtp.h:14,
                 from ../src/media-server_wrap.cxx:1623:
../media-server/include/codecs.h: At global scope:
../media-server/include/codecs.h:126:25: warning: ‘MediaFrame::Type GetMediaForCodec(uint8_t)’ defined but not used [-Wunused-function]
 static MediaFrame::Type GetMediaForCodec(BYTE codec)
                         ^~~~~~~~~~~~~~~~
medooze-media-server.target.mk:211: recipe for target 'Release/obj.target/medooze-media-server/src/media-server_wrap.o' failed
make: *** [Release/obj.target/medooze-media-server/src/media-server_wrap.o] Error 1
make: Leaving directory '/root/media-server-node/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 4.15.0-36-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--jobs=max"
gyp ERR! cwd /root/media-server-node
gyp ERR! node -v v10.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! medooze-media-server@0.46.0 dist: `node-gyp configure && node-gyp build --jobs=max && mkdir -p dist && tar cvzf dist/medooze-media-server-`node -e 'console.log(require("./package.json").version)'`.tgz `([ "$(uname)" = 'Darwin' ] && echo "-s |^|medooze-media-server/|") || echo " --transform=flags=r;s|^|medooze-media-server/|"` package.json index.js   README.md lib/* build/Release/medooze-media-server.node`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the medooze-media-server@0.46.0 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-10-16T21_01_36_929Z-debug.log
```

**Comment by murillo128** [comment]
please,  use head.  I run npm version before updating dependencies so it
doesn't compile.

npm package is good thought

**Comment by Nicholi** [comment]
Oh I haven't used the npm package itself, it probably is good. Just wanting a precompiled version.

Builds fine with HEAD, kinda defeats the purpose of a tagged release though. I wonder if maybe that's been the problem all along? As I am typically building off the tags.

**Comment by murillo128** [comment]
It was my fault when tagging this version, should not happen again
