### ISSUE TITLE
Build issue on mac osx v0.64.5

### ISSUE THREAD

**Issue by igrooves** [medooze/media-server-node#82]
Latest version seems to be broken on mac.

```
> medooze-media-server@0.64.4 install /Volumes/GIT/api/node_modules/medooze-media-server
> test -f build/Release/medooze-media-server.node || (node-gyp configure && node-gyp rebuild --jobs=max)

make: *** No rule to make target `Release/obj.target/mp4v2/external/mp4v2/lib/libplatform/io/FileSystem_posix.o', needed by `Release/libmp4v2.a'.  Stop.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 18.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--jobs=max"
gyp ERR! cwd /Volumes/GIT/api/node_modules/medooze-media-server
gyp ERR! node -v v10.15.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
```

**Comment by murillo128** [comment]
seems you are trying to install `medooze-media-server@0.64.4`, could you double check=

**Comment by igrooves** [comment]
It was from a packed install. hence the npm name

https://github.com/medooze/media-server-node/blob/c2662237b61f1faef05d4d0a250e0e5a54547a3c/package.json#L2

I've resolved it somehow by accident. Thanks for your time.
