### ISSUE TITLE
Streamer.close always fails

### ISSUE THREAD

**Issue by maxhawkins** [medooze/media-server-node#86]
```
TypeError: Cannot read property 'emit' of undefined
    at Streamer.stop (/usr/src/app/node_modules/medooze-media-server/lib/Streamer.js:67:16)
    at Conn.stop (/usr/src/app/build/Conn.js:157:23)
```

It's trying to emit an event but Streamer doesn't have an emitter

**Comment by murillo128** [comment]
Thank you for reporting it!
