### ISSUE TITLE
Sometimes Deadlock on RTPSession Stop

### ISSUE THREAD

**Issue by dt-atkinson** [medooze/media-server-node#98]
Me again! I'm getting deadlock when i try to free RTPSession sometimes while benchmarking.
```
[New Thread 0x7f44517fa700 (LWP 12758)]
[Thread 0x7f446effd700 (LWP 12681) exited]
^C
Thread 1 "node" received signal SIGINT, Interrupt.
0x00007f44a181ad2d in __GI___pthread_timedjoin_ex (threadid=139931905156864, thread_return=0x0, abstime=0x0, block=<optimized out>)
    at pthread_join_common.c:89
89	pthread_join_common.c: No such file or directory.
(gdb) bt
#0  0x00007f44a181ad2d in __GI___pthread_timedjoin_ex (threadid=139931905156864, thread_return=0x0, abstime=0x0, block=<optimized out>)
    at pthread_join_common.c:89
#1  0x00007f44a20a48c3 in std::thread::join() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00007f449a469b4e in EventLoop::Stop (this=this@entry=0x8c5cfd8) at ../media-server/src/EventLoop.cpp:178
#3  0x00007f449a49d957 in RTPTransport::Stop (this=this@entry=0x8c5ca60) at ../media-server/src/RTPTransport.cpp:1149
#4  0x00007f449a49d982 in RTPTransport::End (this=this@entry=0x8c5ca60) at ../media-server/src/RTPTransport.cpp:616
#5  0x00007f449a4d3ae4 in RTPSession::End (this=0x8c5c940) at ../media-server/src/rtpsession.cpp:370
#6  0x00007f449a439414 in _wrap_RTPSessionFacade_End (args=...) at ../src/media-server_wrap.cxx:15078
#7  0x0000387b6b6863c1 in ?? ()
#8  0x00007ffc538d8230 in ?? ()
#9  0x00007ffc538d8258 in ?? ()
#10 0x0000000000000000 in ?? ()
```

**Comment by murillo128** [comment]
Could you get a backtrace of all running threads and paste it on a gist? (It can be quite large)

In gdb:
```
thread apply all bt
```

**Comment by murillo128** [comment]
please reopen if it happens again
